services:
  redis:
    image: redis:latest
    container_name: redis-front
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - dev-network
  postgres:
    image: postgis/postgis:latest
    container_name: postgress-front
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5444:5432"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_front:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: dogood-front
    command: bash -c "chmod 777 entrypoint.sh && ./entrypoint.sh && sleep infinity"
    ports:
      - "5000:5000"
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - dev-network
    volumes:
      - ./:/frontend
      - /frontend/node_modules

networks:
  dev-network:
    driver: bridge
    name: dev-network
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    external: false

volumes:
  pgdata_front: