/**
 * @file Automatically generated by barrelsby.
 */

export * from './main/Faq';
export * from './faq/СontactForm';
export * from './footer/footer';
export * from './footer/SocialLinks';
export * from './main/AboutSection';
export * from './main/HeroSection';
