import type { Metadata } from 'next';
import { Montserrat, Roboto } from 'next/font/google';
import './globals.css';
import React from 'react';
import { Header, Footer } from '@/components';
import { ThemeInitializer } from '@/components/layout/theme/ThemeInitializer';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import ToastProvider from '@/components/ToastProvider';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
});

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>): Promise<React.JSX.Element> {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body
        className={`${montserrat.variable} ${roboto.variable} antialiased flex flex-col justify-between min-h-[100vh]`}
      >
        <ThemeInitializer />
        <NextIntlClientProvider locale={locale}>
          <Header />
          <main className="pt-[80px] lg:pt-[72px]">{children}</main>
          <Footer />
        </NextIntlClientProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
